### ISSUE TITLE
Move to Delta org?

### ISSUE THREAD

**Issue by ssundarraj** [GokulSrinivas/pragyan-inhott#1]
Can we move this to delta org. It seems to be nitt/delta related.

**Comment by nym3r0s** [comment]
Will move in due time da. This was lighta urgent.

meanwhile give me permissions on delta. :P

**Comment by ssundarraj** [comment]
Can you post the repo's link on delta here?

**Comment by nym3r0s** [comment]
There is no repo in delta. I don't have the perms to create one.

**Comment by ssundarraj** [comment]
https://github.com/delta/pragyan-inhott
There you go. You should have access to that.

**Comment by nym3r0s** [comment]
moved.
